# Generated by Django 5.1.3 on 2024-12-04 13:24

import django.core.validators
import django.db.models.deletion
import events.validators
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_category_created_at_category_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                validators=[events.validators.datetime_in_future]
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Beschreibung des Events",
                null=True,
                validators=[
                    functools.partial(
                        events.validators.bad_word_filter, *(["doof", "evil"],), **{}
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    events.validators.validate_name,
                ],
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("event", models.CharField(max_length=255)),
                (
                    "nummer",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9]{8}$",
                                "Nummer must be 8 alphanumeric characters",
                            )
                        ],
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
