# Generated by Django 5.1.3 on 2024-12-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_date_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="events.event",
            ),
        ),
    ]
