# Generated by Django 5.1.3 on 2024-12-06 08:08

import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (6, "Awesome"),
                    (5, "Super"),
                    (4, "Good"),
                    (3, "Ok"),
                    (2, "Bad"),
                    (1, "Worst"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[events.validators.validate_review_text],
            ),
        ),
    ]
